/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal project setup and is kept here
// so type-checking works before the first `next dev` run.

